# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "kube-node-admin"
shortDesc: "List nodes and run privileged pod with chroot"
longDesc: >
  Useful for debugging kubernetes nodes.
  Displays list of available nodes to select from.
  Runs a privileged pod that mounts and chroots into the host filesystem.
  Example:
    kubectl plugin kube-node-admin
command: ./kube-node-admin.sh